### ISSUE TITLE
Any verbosity option for `:dep`?

### ISSUE THREAD

**Issue by Czxck001** [evcxr/evcxr#224]
Since it often takes a long time when adding external crate dependencies by running `:dep` command(s), it'd be a helpful to know what's going on or even better to see a progress bar. Is there any way to display verbose messages when running `:dep` command?

**Comment by davidlattimore** [comment]
Thanks, that's a good idea. I'm not sure if I'll get to implementing it soon myself, but if anyone would like to have a go at implementing it, I'm happy to provide whatever guidance is needed.

**Comment by adiSuper94** [comment]
Hi @davidlattimore . I'd like to take a stab at this.

**Comment by davidlattimore** [comment]
Hi @adiSuper94. Great! Most of the time will be spent, not surprisingly in a call to `cargo`. `cargo` is invoked from `run_cargo` in `module.rs`.

One option would be to plumb some kind of progress reporting callback through to `run_cargo`. The repl and the jupyter kernel would probably need to present the progress / status updates in different ways, so could pass different callbacks.

Probably the first thing to do though is to see how practical it is to get both live status updates and json output from `cargo rustc`. The json output is needed so that evcxr can parse it. Hopefully there's some way to get progress reports from cargo that can be passed to the user, while at the same time not messing up the json emitted by rustc.

**Comment by bjorn3** [comment]
The json output of cargo also shows completion messages. For example

```json
{
  "reason": "compiler-artifact",
  "package_id": "cfg-if 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "manifest_path": "/home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0/Cargo.toml",
  "target": {
    "kind": [
      "lib"
    ],
    "crate_types": [
      "lib"
    ],
    "name": "cfg-if",
    "src_path": "/home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0/src/lib.rs",
    "edition": "2018",
    "doc": true,
    "doctest": true,
    "test": true
  },
  "profile": {
    "opt_level": "0",
    "debuginfo": 2,
    "debug_assertions": true,
    "overflow_checks": true,
    "test": false
  },
  "features": [],
  "filenames": [
    "/tmp/foo/target/debug/deps/libcfg_if-fbf140492188e9ae.rlib",
    "/tmp/foo/target/debug/deps/libcfg_if-fbf140492188e9ae.rmeta"
  ],
  "executable": null,
  "fresh": false
}
```

once cfg-if has been compiled. This is what rust-analyzer uses for progress reports. You can use `cargo metadata --filter-platform x86_64-unknown-linux-gnu` to get the full list of crates that will be built. Another thing is that cargo prints the json messages on stdout, but still keeps it's human readable output on stderr.

**Comment by adiSuper94** [comment]
@davidlattimore 
The function `commnad.ouput` that is called in `run_cargo` is a synchronous function. 
So I guess we wait till it genarates all of the output.
Should we use the async version of `process::command`?  This should get us the live updates.

I think we should be able to construct the original json using the live stream, and sent to evcxr for parsing.

**Comment by davidlattimore** [comment]
I don't think it should be necessary to use async (as in async/await), however you would need to not call `Command::output` and instead call `Command::spawn`. You can then receive output from the subprocess as it is sent.

**Comment by adiSuper94** [comment]
@davidlattimore, I just raised a PR. 
It is very much WIP. 
But I'd still like your comments on it.
