### ISSUE TITLE
Error when opening two notebooks at the same time.

### ISSUE THREAD

**Issue by baiguoname** [evcxr/evcxr#302]
When I am running two notebooks at the same time, the following error occur:
`Error copying '"D:/evcxr_tmpdir\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.dll"' to '"D:/evcxr_tmpdir\\target\\x86_64-pc-windows-msvc\\debug\\deps\\code_10.dll"': 另一个程序正在使用此文件，进程无法访问。 (os error 32)`
After I close the other notebook, this error disappear.
The environment is jupyter notebook extension on vscode in windows.

**Comment by davidlattimore** [comment]
It looks like you're using a non-unique temporary directory. I'm guessing you've got `EVCXR_TMPDIR` set?

`EVCXR_TMPDIR` is mostly intended for debugging purposes, since it forces Evcxr to use a single temporary directory - which is handy when you want to see what Evcxr is doing, but does mean that only one copy of evcxr can be run.
