### ISSUE TITLE
Macro `print!` doesn't work.

### ISSUE THREAD

**Issue by baiguoname** [evcxr/evcxr#303]
I have the following code in notebook in vscode in windows:
![image](https://github.com/evcxr/evcxr/assets/52092777/d450e0ca-c797-43e2-b82d-872a0a617bab)
It has no output, I guess the macro `print!` doesn't work.

**Comment by davidlattimore** [comment]
Evcxr buffers output line by line. println! should work

**Comment by baiguoname** [comment]
Thanks for your reply.
Is there a way I can print output in evcxr sequentially? I am trying to implement a progressbar in evcxr like this, but without being able to print out the infomation in the same line, the functionality would be limited.
![image](https://github.com/evcxr/evcxr/assets/52092777/57bc31ea-e28a-420a-b5eb-6ffde86b4280)

**Comment by davidlattimore** [comment]
I don't think there is at present. It would probably be possible to pass through output as it came, but would require some changes to Evcxr. The main issue is that Evcxr uses stdout to communicate from the subprocess that runs the user code to the parent evxcr process. It sends information about panics, problems with variables as well as mime-encoded outputs (mostly relevant for the Jupyter notebook).

All of these are printed on lines that start with "EVCXR_", so it would be possible to read content and pass it through provided it wasn't "EVCXR_" or some prefix thereof.

Somewhat more simple would be to change stderr to not be line-based. It's not used for any such communication and is only line based because it shares code with the stdout handling code.
