### ISSUE TITLE
Relative path dependency on Windows not working

### ISSUE THREAD

**Issue by ahwatts** [evcxr/evcxr#62]
I'm having trouble loading a relative path dependency on Windows.  The cell looks like this:

```
:dep num = "^0.2.0"
:dep num-complex = "^0.2.3"
:dep organic-snout = { path = ".." }
:dep plotters = { git = "https://github.com/38/plotters", default_features = false, features = ["evcxr"] }
```

And the output is:

```
Compilation failed, but no parsable errors were found. STDERR:
error: failed to parse manifest at `C:\Users\ANDREW~1\AppData\Local\Temp\.tmpxYNfAx\Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  invalid escape character in string: `C` at line 25

STDOUT:
```

I've verified that the organic-snout dependency is the one causing the problem. If I comment it out, the cell evaluates cleanly.

If I go and look at the `Cargo.toml` that the error message refers to, it looks like this:

```
[package]
name = "ctx"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = 2
debug = false
rpath = true
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[dependencies]
num = "^0.2.0"
num-complex = "^0.2.3"
plotters = { git = "https://github.com/38/plotters", default_features = false, features = ["evcxr"] }
organic-snout = { path = "\\?\C:\Users\Andrew Watts\Projects\organic-snout" }
```

I'm not sure what that goofiness is at the beginning of the path, but clearly Cargo is confused by it, too.

**Comment by davidlattimore** [comment]
Thanks for the report and the detailed diagnostics! I might not get a chance to look at this for a bit longer, but hopefully will within the next couple of weeks. I also don't have Windows, so wouldn't be able to be 100% sure if I've fixed it. So if you or anyone else wanted to have a go at fixing this in the mean time, just say so :)

I'd say the problem would be the function make_paths_absolute. It's worth noting that the comment at the start of that function no longer really applies. The problem I was trying to avoid by not using a toml parser is now long gone and we've since dropped support for older versions of rustc.
